
# Configura o Hibernate para criar/atualizar as tabelas automaticamente.

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Configuração do OpenAPI/Swagger
springdoc.swagger-ui.path=/swagger-ui.html