# Configuração do Servidor Web

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

# Configuração do OpenAPI/Swagger
springdoc.swagger-ui.path=/swagger-ui.html